services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    networks:
      - app-tier
    volumes:
      - ./logs:/logs

  db:
    image: postgres:latest
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-tier

  migrations:
    image: kukymbr/goose-docker:3.24.2
    container_name: migrator
    command: up
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME}
      - GOOSE_MIGRATION_DIR=${GOOSE_MIGRATION_DIR}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "sh", "-c", "exit 0" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./migrations:/migrations
    networks:
      - app-tier

volumes:
  postgres_data:


networks:
  app-tier:
